export {default as Home} from "./buttons/home"
export {default as Searchbar} from "./buttons/searchbar"
export {default as UnloggedProfile} from "./buttons/unlogged_profile"
export { default as AnimationCard} from "./buttons/animationcard"
export { default as InterfacePlayer} from "./Interface/Player"
export { default as InterfaceView} from "./Interface/landing"
export {default as AnimationPlayer } from "./buttons/animationplayer"